### ISSUE TITLE
Deployed 20.09, but unable to get Controller UI

### ISSUE THREAD

**Issue by AmanThakral02** [open-ness/converged-edge-experience-kits#68]
We are following the document [OpenNess-Network-edge](https://www.openness.org/docs/doc/getting-started/network-edge/controller-edge-node-setup) to enable the Controller UI. It seems the document is not updated for release 20.09, as we are unable to find the .env file to update INFRASTRUCTURE_UI_URL.

Please guide me to updated documentation.

Below are the cluster snippets, please let me if more details required.

[root@edgecontroller2 opt]# kubectl get pods -n openness
NAME                                                       READY   STATUS    RESTARTS   AGE
docker-registry-deployment-54d5bb5c-rngpc                  1/1     Running   0          27h
eaa-5c87c49c9-48kjq                                        1/1     Running   0          14h
edgedns-c9vtq                                              1/1     Running   0          14h
interfaceservice-ddbjz                                     1/1     Running   0          14h
nfd-release-node-feature-discovery-master-b5d78f89-vn5bf   1/1     Running   0          26h
nfd-release-node-feature-discovery-worker-26w77            1/1     Running   0          14h

**Comment by amr-mokhtar** [comment]
Hi @AmanThakral02 
The controller UI is now automatically installed as part of the OEK. The above section in the Getting Started guide is obsolete. We will remove that section.
Please refer to [this page](https://www.openness.org/docs/doc/enhanced-platform-awareness/openness-kubernetes-dashboard) in order to get the dashboard installed
